### ISSUE TITLE
About switching themes

### ISSUE THREAD

**Issue by sdjxxfz** [m1k1o/neko#148]
The system default is black theme, which causes all websites to become black theme, can you provide the function to switch to white theme?

**Comment by m1k1o** [comment]
This was introduced to firefox in this commit: https://github.com/m1k1o/neko/commit/b9675a1c8711fb0eb41a46e436c24b3b85ce1176

And in chromium it is forced here with `--force-dark-mode`:
https://github.com/m1k1o/neko/blob/ba3368a3eb6bad6287ee1a4b908b4921dc3099df/.docker/chromium/supervisord.conf#L3

You can revert/remove it if you like tight theme. Having switch is non-trivial, because it affects inital browser configuration and arguments, that cannot be modified from go server itself.

**Comment by sdjxxfz** [comment]
Wow thank you very much! But may I ask what to do with google chrome?

**Comment by yesBad** [comment]
`--force-dark-mode`:
https://github.com/m1k1o/neko/blob/ba3368a3eb6bad6287ee1a4b908b4921dc3099df/.docker/google-chrome/supervisord.conf#L3

**Comment by sdjxxfz** [comment]
Just saw it, thank you

**Comment by sdjxxfz** [comment]
I tried my best to find this file in my docker container /etc/neko/supervisord.conf but the content in it is way different from given above. What should I do?

**Comment by m1k1o** [comment]
Its in `/etc/neko/supervisord/chromium.conf` or different browser name.
https://github.com/m1k1o/neko/blob/ba3368a3eb6bad6287ee1a4b908b4921dc3099df/.docker/chromium/Dockerfile#L32

**Comment by sdjxxfz** [comment]
it works! Thank you very much for you help and such a good project!
