### ISSUE TITLE
Hardware acceleration?

### ISSUE THREAD

**Issue by IngwiePhoenix** [m1k1o/neko#228]
I have moved my Neko instance across servers several times by now and really love it. But I finally have a server that has some good GPU to it and I would love to utilize that, mainly because software rendering is a bit troublesome on this specific system.

So, I would like to know if:
- ...i can run hardware accelleration in docker?
- ...I can install Neko "natively" instead so it has full access to the hardware?

The device is a FriendlyElec NanoPi R6s - 4+4 ARMv8 with a pretty neat iGPU.

Thanks!

**Comment by m1k1o** [comment]
Currently there has been added support for only vdpau/vaapi hardware acceleration [for encoding the video stream](https://github.com/m1k1o/neko/issues/119). I don'ŧ know if that can be used in your NanoPi.

For hardware acceleration inside neko, so that the apps (browser) can use GPU, there is already [similar issue](https://github.com/m1k1o/neko/issues/226).

You could be able to `install Neko "natively"`, I have tried it in one VM. Although there is not proper documentation about this, you would just need to follow steps that are in [Dockerfile](https://github.com/m1k1o/neko/blob/4789b7704f386cc456504d2644c921cdf936ee49/.docker/base/Dockerfile), install on your host system and then just run it. However, I recommend starting with exsiting system that has GUI with desktop manager, is based on Xorg and uses Pulseaudio. For that matter you only need to install gstreamer dependencies, configure pulseaudio properly and run neko binary (you don't need to build it from scratch, you can copy it from docker image). This process would be nice to have documented.

You could theoretically just expose your host's Xorg server inside neko container and it would control your host system. In that case, it would be a nice addition to create lightweight container only for this puropse. You could use `m1k1o/neko:base` for it, but it contains Xserver that would not be used by you. But getting audio to work this way is additional effort.

**Comment by IngwiePhoenix** [comment]
> Currently there has been added support for only vdpau/vaapi hardware acceleration [for encoding the video stream](https://github.com/m1k1o/neko/issues/119). I don'ŧ know if that can be used in your NanoPi.

```
root@FriendlyWrt /sdcard# ffmpeg -hide_banner -hwaccels
Hardware acceleration methods:
vdpau
vaapi
drm
vulkan

root@FriendlyWrt /sdcard# tree -a /dev/dri
/dev/dri
├── card0
├── card1
├── renderD128
└── renderD129
```

No problem :)



> ollow steps that are in [Dockerfile](https://github.com/m1k1o/neko/blob/4789b7704f386cc456504d2644c921cdf936ee49/.docker/base/Dockerfile),

Good call...will give it a shot. I also have not spotted any documentation about native installation.

> You could theoretically just expose your host's Xorg server inside neko container and it would control your host system.

That is possible? I never really got the hang of Xorg/Wayland...so I wouldn't know. But this might work quite well.

Thank you for your insights, this'll definitively keep me occupied for a while =)

**Comment by yatli** [comment]
I've hacked together a working POC here: https://github.com/yatli/neko/commit/59df4c661e13acf0c172c8a513fce95668f3c37f

- NVIDIA proprietary driver works best. nouveau lags so badly the performance is not as good as CPU.
- Driving a real graphics card from within docker means a lot of permission/ownership hacks. `/dev/tty{0..6}, /dev/nvidia*, /dev/dri/*` etc.
- NVIDIA driver inside the container must match the version of the host driver
- Start the container, `nvidia-xconfig` and extract the content into `xorg.conf` (included in the commit) -- otherwise it gets stuck at 640x480
- All the standard modes can be specified directly like `mode "1920x1080"`.
- I did not get HWENC working. Black screen. Tried both nouveau and propri driver. May need to expand the video pipeline construction code to support different drivers.
- X starts slow, dbus dies too many times before it could have a chance to connect, and supervisord gives up

**Comment by m1k1o** [comment]
@yatli what run command did you use? It fails for me:
![image](https://user-images.githubusercontent.com/7534274/211655384-d8030980-d409-42f2-afe2-3a53bb303e8c.png)

Did it use your external screen?

**Comment by yatli** [comment]
Nothing special, just `docker-compose up` the locally built image.

> Did it use your external screen?
Yes. My home server is connected to the TV.

You can shell into the container and "neko" the Xorg.99.0.log file to see what's gone wrong. Usually it's a permission issue. Aside from SYS_ADMIN, I also need to `chown -R 1000:1000 /dev/nvidia*` etc. etc.

**Comment by m1k1o** [comment]
Nvidia GPU acceleration has been merged.
