### ISSUE TITLE
Un-minimizing Chrome 

### ISSUE THREAD

**Issue by innerop** [m1k1o/neko#285]
Hi @m1k1o ,

I minimized Chrome and was not able to bring it back up unless I log out and login again.

Is there another way to bring it back up?

**Comment by m1k1o** [comment]
That would be the task of display manager (like kde or xfce), but for browser they are not installed. So there is no way of un-minimize anything. It would be nice to find some lightweight display manager, that either shows minimized programs or automatically un-minimizes them so that people do not end up stuck having their program minimized.

Actually, we are [trying to hide window decoration](https://github.com/m1k1o/neko/blob/b2080649ea50d942c3e9887813d867edbfc21052/.docker/google-chrome/openbox.xml#L17) (maximize, minimize and close button). But some programs such as google chrome show them anyway.

**Comment by innerop** [comment]
It's weird that Chrome is ignoring the window manager config for no decoration.

I see that you have a large <keyboard> section in openbox.xml and my guess is you're already using openbox, or is the file there but openbox is not loaded? 

There is a large keyboard section in the included openbox.xml, so I can try the shortcuts for switching between apps and see if that brings it up after being minimized but I googled around and the shortcuts for toggling minimize/maxmize is 

```
<keybind key="C-A-x">
  <action name="ToggleMaximize"/>
</keybind>
```

**Comment by innerop** [comment]
@m1k1o 

I set that to true and cleared docker cache and rebuilt the google-chrome docker (not the base tho) and docker-compose up, still i see the minimize, maximize and close buttons. Hmm.

**Comment by innerop** [comment]
Will close for now since it seems to be an issue with google chrome itself. May work fine for ungoogled-chrome or chromium or firefox et al.

**Comment by m1k1o** [comment]
There is a way, you need to have installed `xdotool` and then just `xdotool windowminimize $(xdotool search --name chrome)`.

**Comment by innerop** [comment]
Ok, that's good to know. Sorry, I've got busy with a new project, and will circle back here when done. Thanks for this tip. I've never heard of xdotool.
