### ISSUE TITLE
Questions about PRs contribution and development environment

### ISSUE THREAD

**Issue by innerop** [m1k1o/neko#286]
On PRs, 

the .env.default in .docker I assume is only used for starting server and serving client when developing with the server and you don't want to rebuild the base image each time. It diverges from the docker compose config in several places like the UDP port range and using separate ports for client and server. 

I also noticed in server.go the http/ws port on the host is hardcoded to 8080 but start-server takes the var from .env.default for the port on docker.  

Also, I didn't get the part in the getting started doc on why the docker port has to match the host port. I recall having done arbitrary mapping on my docker apps before.

**Comment by innerop** [comment]
One more question:

"Libclipboard files can be retrieved from neko_dev_server container:"

Are these needed when recompiling the server for local testing (without rebuilding the base image) ?

**Comment by m1k1o** [comment]
> the .env.default in .docker I assume is only used for starting server and serving client when developing with the server and you don't want to rebuild the base image each time.

Yes, it is only simplified development environment. Since neko needs many dependencies, not everyone want to install them to change just minor things. We could have [development in a container](https://code.visualstudio.com/docs/devcontainers/containers), but that would be different environemnt that the production and we would need to maintain both of them.

> It diverges from the docker compose config in several places like the UDP port range and using separate ports for client and server.

That is purely for debugging, so that you can start interactive npm client server. That means, if you change something in client you don't need to recompile full neko. In order to use this different client, you need to bypass [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) because server and client are on different port. That is solved by proxying everyting from client port to the server.

> Also, I didn't get the part in the getting started doc on why the docker port has to match the host port. I recall having done arbitrary mapping on my docker apps before.

That is only for WebRTC, because it sends `server-ip:server-port` to the client and client is going to connect to that. If you would change port nubmers, they would not be valid. And neko has no way of knowing what is the actual port number (without STUN server).

> Are these needed when recompiling the server for local testing (without rebuilding the base image) ?

Yes, if you would do it on your host without docker image, you would need `libclipboard` dependency. You can either build it (looking into Dockerfile how its done) or just copy the libraries that were built inside docker.

**Comment by innerop** [comment]
Thanks, I was just noticing things at a glance, and not paying much attention. 

It makes sense now.

**Comment by innerop** [comment]
maybe we need to add that to the docs

i already got the clipboard stuff from the container
