### ISSUE TITLE
HTTP Port change not working

### ISSUE THREAD

**Issue by NN-Binary** [m1k1o/neko#297]
Hi,

When changing port 8080 to 8082 in docker-compose.yaml
```
        ports:
            - "8082:8082"
            - "52101-52201:52101-52201/udp"

```

It isn't reachable anymore, locally or externally, port 8080 (default) works fine, but basically any other port does not work, is it an ongoing issue? Is there a special setup to do?

NOTE: The docker container starts and is up and running, it's simply not accessible anymore via http://ip:8082

**Comment by m1k1o** [comment]
Hi, you need to keep the port inside docker `:8080` since you are only changing your port ooutise of docker. Therefore change it to `"8082:8080"`

https://neko.m1k1o.net/#/getting-started/?id=why-so-many-ports
![image](https://user-images.githubusercontent.com/7534274/233804359-cfaaaca2-fc6d-4c4f-ad6b-bb2a23b03345.png)

**Comment by NN-Binary** [comment]
Thank you, indeed it works!
