### ISSUE TITLE
Using external ICE server stun/turn

### ISSUE THREAD

**Issue by W0rmsy** [m1k1o/neko#34]
Hello,

I don't know if it's the right place to ask the question or if I should ask in the original repo.

I would like to install neko in my home lab and expose it on internet. The issue is that I have only a single public IP and multiple services are currently using ICE/stun/turn. I can't therefore forward those port to Neko.

I've however a coturn installed and it works well with my other apps. The question now is how to tell Neko to use that server and not the one built-in

I've configured the reverse proxy on my web server. - That part works well

I've tried on nurdism build to add in the docker-compose the following
```
- NEKO_ICELITE: 0
- NEKO_ICESERVER: 'stun:<my-stun.tld:port> turn:<my-turn.tld:port:secret>'
- NEKO_IP: <my public ip>
- NEKO_NAT1TO1: <private ip of neko>
```

but I have no clue how to specify the turn server, how should I put the secret, etc...
It works if I connect from another machine from inside, but doesn't works from outside.

I'm now running m1k1o/neko:latest but still don't know how to use an external turn.

Thanks for your help !

**Comment by m1k1o** [comment]
Hello,

passing secrets to TURN / STUN servers is not implemented at the moment. What you already tried to do is basically everything you can do, right now.

However, it is not such problem to introduce this functionality, since underlying [WebRTC Pion](https://github.com/pion/webrtc) is supporting this feature, as well as JS clients. The only thing that is missing is passing those secrects to them from config.

Me personally, and most of the usecases don't need STUN / TURN servers when using `NEKO_ICE_LITE`, neither needs additional TCP compatibility. That can be why this feature is missing.

**Comment by mbattista** [comment]
I could implement and test it, since I also have a self hosted coturn with credentials.

Would you be ok with the following implementation:
- `iceserver` config var gets changed to string at `server/internal/types/config/webrtc.go`
- NEKO_ICESERVER does not start with `{`
  - `iceserver` config var gets changed to `{ URLs: %s },`
- ` server/internal/webrtc/webrtc.go` will use the string directly in the `webrtc.configuration`

Alternative it would be possible to use viper to read in a string map. This would probably a change that would break existing configuration.

**Comment by m1k1o** [comment]
I like the idea of extending that field using colon separation, with the syntax introduced by @W0rmsy:

```
stun:<host>:<port>:<user>:<credential>
turn:<host>:<port>:<user>:<credential>
```

That would also ensure backward compatibility for clients, where no credential is being used:

```
stun:<host>:<port>
turn:<host>:<port>
```

Only disadvantage would be, that password cannot contain colon. That could be either
 - ignored
 - escaped by backward slash `turn:<host>:<port>:my\:password:with\:colon`
 - escaped by urlencode `turn:<host>:<port>:my%3Apassword:with%3Acolon`
 - or having username/password base64 encoded
   - implicit `turn:<host>:<port>:bXk6cGFzc3dvcmQ=:d2l0aDpjb2xvbg==`
   - explicit `turn:<host>:<port>:base64:bXk6cGFzc3dvcmQ=:without_colon`

Or we could introduce new config key named `NEKO_ICESERVERS` that would read config as map. Having both of the config keys joined, with servers with & without credential.

**Comment by mbattista** [comment]
I dont think that this syntax is sufficient.

```
type ICEServer struct {
	URLs           []string          `json:"urls"`
	Username       string            `json:"username,omitempty"`
	Credential     interface{}       `json:"credential,omitempty"`
	CredentialType ICECredentialType `json:"credentialType,omitempty"`
}
```
Example via https://pkg.go.dev/github.com/pion/webrtc/v3#ICEServer

The URLs are an array for each ICEServer element to signal the order of importance within one server.

While it is possible to split the same server in multiple entries, which would happen with a colon separated list which EACH having their own credentials, this would result in waiting for multiple timeouts of the same server instead of a single one, if the server is not available.

I would prefer to stay as close as possible to the syntax used in pion.

**Comment by m1k1o** [comment]
Yeah, you are right. That could introduce bottleneck in the future. Sticking to original struct seems to be the best approach.

**Comment by W0rmsy** [comment]
> 
> 
> I could implement and test it, since I also have a self hosted coturn with credentials.
> 
> Would you be ok with the following implementation:
> 
>     * `iceserver` config var gets changed to string at `server/internal/types/config/webrtc.go`
> 
>     * NEKO_ICESERVER does not start with `{`
>       
>       * `iceserver` config var gets changed to `{ URLs: %s },`
> 
>     * ` server/internal/webrtc/webrtc.go` will use the string directly in the `webrtc.configuration`
> 
> 
> Alternative it would be possible to use viper to read in a string map. This would probably a change that would break existing configuration.

That would be wonderful :)
