### ISSUE TITLE
A way to have new users unmuted by default?

### ISSUE THREAD

**Issue by DillFrescott** [m1k1o/neko#65]
This would be fantastic because if a user is joining, I'd like to have the option of having the music/show or whatever not being muted by default.

This would also help because sometimes my internet glitches and Neko reloads, which resets it back to muted, requiring me to go to the window and unmute the music again. :/

**Comment by mbattista** [comment]
For me, the video is always unmuted when I login via the login screen, but is always muted when I reload or use an autojoin link.

I tried to unmute the video after an fixed time instead of a click and got this error from chrome:
```
Unmuting failed and the element was paused instead because the user didn't interact with the document before. https://goo.gl/xX8pDD
```

So this is an browser feature which cannot be avoided. The "Autoplay Policy" dictates that the user has to interact with the page before a sound can be played, even on a reload of the page.

But we try to handle the reconnects better #48 , which will hopefully lead to less reloads required.

**Comment by DillFrescott** [comment]
Thank you! @mbattista

**Comment by m1k1o** [comment]
After reconnects the page itself does not reload, so it should be able to keep unmuted. I'll look into it.
