### ISSUE TITLE
[Feature Request] One Man Show option

### ISSUE THREAD

**Issue by netrules** [m1k1o/neko#90]
## Description

**As an** admin of a n.eko `m1k1o/neko:vlc` station/instance,
**I want to** be the only person with controls over content being distributed to vieweing parties, by using a "flag" or "mode"  in the runtime configuration.
**So that** I can provide an exclusive experience, in order to disable user interaction within the UI and signal listeners in the API for requesting controls or modifications from regular members.

## Technical

- Variant example of use case instance — Admin Control: `EVENT.ADMIN.CONTROL`
Not to be disabled. This can force a user with ADMIN role to _steal_ or _take_ controls by force, however, it should also be possible for an admin to use the regular control event `EVENT.CONTROL.LOCKED` as an ideal use case interaction, but NOT for regular members.

- Global setting
Viper flag/mode called "`NEKO_ADMIN_MODE`", when set to true, the introduced feature being requested will make sure several things happen. [In the websocket](https://github.com/m1k1o/neko/blob/dev/server/internal/websocket/session.go#L41), by using `session.Admin()` and the flag, it can make sure to notify the user connection through the `SessionConnected` method to disallow control features. Thus, making sure `this.$accessor.remote` [webrtc action requests](https://github.com/m1k1o/neko/blob/dev/client/src/store/remote.ts#L60) as limited to be used only by admin roles.

- Additional presentation factors
We make sure to disable the corresponding logic behind presentation. i.e: [video component](https://github.com/m1k1o/neko/blob/dev/client/src/components/video.vue#L638-L640), [controls component](https://github.com/m1k1o/neko/blob/dev/client/src/components/controls.vue#L288-L304), [remote store additional logic](https://github.com/m1k1o/neko/blob/dev/client/src/store/remote.ts#L20-L28).

- Backend securing
Then, we make sure controls are only enabled to admins in [websocket control](https://github.com/m1k1o/neko/blob/dev/server/internal/websocket/control.go) **only if the** flag feature is enabled. This can be done by a condition in the beginning of each method and then returning false. Or, alternatively, only enabling [these events](https://github.com/m1k1o/neko/blob/dev/server/internal/websocket/handler.go#L70-L91) for admin roles.

## Result
Admins can now host a session where users are limited to watching, interacting with each other, controlling local settings such as volume and play/pause-ability, but not admin features, such as broadcasting or screen, as well as internal control features. This will allow admins to have the sole control of what is being seen on demand.

## Conclusion
Let me know if I missed anything, I can get started on this PR and submit it some time soon if others approve of the need for this feature and would like to see it implemented.

**Comment by m1k1o** [comment]
The broadcast feature should mimic part of this, where you can cast your content to YouTube, for example, and gain a wide watch-only audience. That also means outsourcing user control to a third party app, also custom chat on their page.

When we would have watch-only users, then there is no need for an ultra-low latency WebRTC stream, that we are providing now. That causes [low deadline for transcoding](https://github.com/m1k1o/neko/blob/89f4e697c24b93589a4eb53a60c9521fcc8f0917/server/internal/gst/gst.go#L98), what can lead to lower video quality and higher bandwidth usage. For such users, there would be sufficient also HTTP based streaming, like [HLS](https://en.wikipedia.org/wiki/HTTP_Live_Streaming) or [DASH](https://en.wikipedia.org/wiki/Dynamic_Adaptive_Streaming_over_HTTP), that can be easily [cached](https://www.theoplayer.com/blog/comparing-webrtc-with-http-based-streaming) by the web server (there is already an issue for that in upstream repository https://github.com/nurdism/neko/issues/77).

Also, I think instead of taking ability for users to control based on global server config, we should add a new access layer (admin, user, viewer) again, with own password. Although, that lead to complicated UX. Even now, with two passwords, some users are struggling to find the correct username, failing to understand, that there are no accounts.

Maybe a good solution to this would be adding a lock. We have already [room lock](https://github.com/m1k1o/neko/blob/89f4e697c24b93589a4eb53a60c9521fcc8f0917/server/internal/websocket/handler.go#L37-L40), so that no users can join (those already joined can stay until they are kicked out or leave). Having another lock for the controls, that would allow only admins to gain controls and no users, could be a neat feature. In that case, we don't need to deal with another access layer or server config, and users controls can be anytime re-enabled.

## Conclusion

Features/changes suggested by you are relevant and very welcome, except I would rather give that toggle on the frontend for the admins, instead of a viper flag/mode. Because having users without possibility to enable control for them somehow loses the original use cases for this project - collaborative browser. Going for that option, it could rather be leveraging better streaming options (such as HTTP streaming) for better user performance.

**Comment by netrules** [comment]
Thank you, great feed back. I will look into how I will do it that way then. The HTTP streaming option sounds amazing for less error probability, seeing how there won't be such a small margin for allowing connection issues, but instead a wider range of fallback options that other protocols such as HLS present for handling desynchronizations as well as packet loss. Caching in the server would also be an excellent feature for preventing overly bandwidth consumption, no?

 Anyway, that was great input. I am not sure if there is, but, is there an option to default options in the room instead of having to setup everything each time? Would be nice to have **control lock** already enabled by default if this is indeed added,

**Comment by mbattista** [comment]
When I read the Issue, my first reaction was "just never release the controls as admin?" Other Admin should be able to grab the controls and normal user could only request but never take the controls. But I understand where your idea is coming from, since the admin could drop the connection or join late, which then could lead to a user having control.

I think this feature could improve some cases, while in most cases the change is not even noticed (disabled by default etc).
Perhaps with three passwords the users struggling with the concept of having no accounts will decrease since there are more examples in the README?

For the HLS / DASH discussion I have to add, that firstly you probably should not look into HLS. From my understanding HLS will not get webm support with any modern codec. [DASH](http://wiki.webmproject.org/adaptive-streaming/instructions-to-do-webm-live-streaming-via-dash) would be possible similar how the broadcast feature is implemented now, that it is simply another pipeline that gets started. n.eko could possible even serve a website with a shaka player to play the new pipeline.

BUT I am not a big fan of this idea.
Firstly I only see marginal improvements in quality over the webrtc version. Since it is still live streaming you still have the low deadline for transcoding. While having TCP for dropped packages is good, webrtc also has a mechanism to handle dropped frames.
Secondly you already have a perfectly fine pipeline, which consumes some cores (depending on your hardware). While never Hardware can probably handle two or three pipelines, older hardware will not. With the rise of AV1 even newer hardware could probably get problems when starting multiple pipelines.
Thirdly for me n.eko is the tool for sharing a virtual desktop / browser with your friends. If you just want to stream a video to people and not have them interact you could use [stream m](https://github.com/vbence/stream-m) with OBS for example.

**Comment by m1k1o** [comment]
Never releasing control is also what I used earlier, but it only works when an admin with a stable connection is present in the room. Otherwise, it must be shut down to protect the control.

I agree that HLS/DASH streaming might be out of scope and resource-intensive solution on HW. We should rather focus on smoother delivering of our existing pipelines to all users instead of creating new one.

Having a simple control lock along with our room lock could be a nice solution. And possibility to set **initial values** to those locks using config (ENV vars). Adding some protection, when last admin leaves (or is disconnected) then control will be after some time locked, might sound interesting.

My proposal would be:

- `NEKO_ROOM_LOCK=true`
- `NEKO_CONTROL_LOCK=true`
- `NEKO_CONTROL_PROTECTION=true`

When having protection enabled, users could only get control when at least one admin is in the room.

Having a third password could be also an option, but that user could never get control - what is the point of a shared browser. As @mbattista pointed out, for that use-case other tools can be used.

**Comment by netrules** [comment]
Alright. I'm still here by the way, just haven't had time to approach this subject. I will begin working on the feature through env vars and zero-admin checks. Will also add a button for control protection.

Question: admins should still be able to join/leave freely should the room be locked, _correct_?

**Comment by m1k1o** [comment]
We already have room lock implemented, and admins can join and leave. That affects only users. I think, also with control lock, it should only affect users. If you log in as admin, you should get always full privileges regardless of current state in the room.

**Comment by elixx** [comment]
Kind of related, is there any way to not require any password for viewers/users? Commenting out / removing NEKO_PASSWORD appears to default to `neko`

**Comment by m1k1o** [comment]
Passwords are needed. But you can include password in URL so that user does not need to type it. E.g. use default password `neko` and send your friends / bookmark this link: `http://<your-neko-instance>/?pwd=neko`. Once visiting that page, password is saved to local storage, so the next visit does not need to enter any password.

**Comment by netrules** [comment]
Still here by the way. Going to do this really soon, have been super busy with work IRL. Thanks for patience!

**Comment by m1k1o** [comment]
Control lock has been implemented:
![image](https://user-images.githubusercontent.com/7534274/142074460-ff0ed8dd-6399-4796-bfa3-7428621a94e0.png)

And also setting locks from config with `NEKO_LOCKS=control login`.

**Comment by m1k1o** [comment]
Control protection has been implemented. Users can gain control only if at least one admin is in the room `NEKO_CONTROL_PROTECTION=true`. So that when last admin leaves, control will be locked and when first admin joins, controls are unlocked.

Both of these features (control protection & locks) should complete this freature request. Pleae let me know if that works for you.

**Comment by netrules** [comment]
![image](https://user-images.githubusercontent.com/48886164/142566479-756be05d-56d8-4f2e-b8d2-af40f88916a7.png)
